[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
ss_back = "46s1CHb7PQHHJJ7F3MetxcEriy9aBYD4PVb93GBe8ig2"

[programs.devnet]
ss_back = "46s1CHb7PQHHJJ7F3MetxcEriy9aBYD4PVb93GBe8ig2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 20000